[project]
name = "osu-mapper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "tensorflow[and-cuda]>=2.20.0",
    "numpy>=1.26.0",
    "librosa>=0.10.0",
]
